### ISSUE TITLE
[Feature] Share example of configuration of triggers on job completion

### ISSUE THREAD

**Issue by pikachuev** [dbt-labs/dbt-jobs-as-code#108]
**Describe the feature**
Could you please share how to write properly configuration for option 'Job completion':
![image](https://github.com/user-attachments/assets/a5e6b7d0-8125-4745-82f7-6cfdf7879080)

**Comment by b-per** [comment]
Hi!

If you use [the JSON/YAML schema](https://github.com/dbt-labs/dbt-jobs-as-code#job-configuration-yaml-schema), it should give you some hints of what is expected.

You need to add this config

```yaml
    job_completion_trigger_condition: 
      condition:
        project_id: 123
        job_id: 123
        statuses:
          - 10
```

And hovering on `statuses` will tell you what status number corresponds to what "humanized" status

![image](https://github.com/user-attachments/assets/dbc87206-6f96-4ed7-b3dd-a5786435ecc9)
