### ISSUE TITLE
[Feature] Provide the ability to post the results of the `plan` to GitHub, as a comment

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-jobs-as-code#129]
Today, people have to go through the CI/CD logs in order to see if changes have been identified as part of a `plan` on PR creation.

We should provide a way, even if it just a GitHub actions code to copy/paste, to allow people to see the results of the `plan` directly in the GitHub PR that was raised

**Comment by b-per** [comment]
The following code works. Let's add it to the docs.



```
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"
      - name: Install dbt-jobs-as-code
        run: pip install dbt-jobs-as-code

      - name: Run dbt-jobs-as-code
        id: jobs-as-code-plan
        run: |
          printf "Changes from dbt-jobs-as-code (full details are available in the actions logs):\n\`\`\`\n" > plan_output.txt
          dbt-jobs-as-code plan jobs/my_jobs.yml --vars-yml jobs/prod_vars.yml --limit-projects-envs-to-yml >> plan_output.txt
          printf "\n\`\`\`\n" >> plan_output.txt
        env: 
          DBT_API_KEY: "${{secrets.DBT_API_KEY}}"
          # DBT_BASE_URL is optional
          # DBT_BASE_URL: "${{secrets.DBT_BASE_URL}}"

      - name: Comment PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: plan_output.txt
```
