### ISSUE TITLE
[Feature] Allow `validate` step to fail if multiple jobs with the same key are found in `jobs.yml` file

### ISSUE THREAD

**Issue by justbldwn** [dbt-labs/dbt-jobs-as-code#149]
**Describe the feature**
We'd like to prevent developers from defining multiple jobs with the same key in their `jobs.yml` file, ideally in the `validate` command. The below behavior is what we detected when testing this:

**Example `jobs.yml` file**
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jobs-as-code/main/src/dbt_jobs_as_code/schemas/load_job_schema.json

jobs:
  test_job:
    account_id: 111
    project_id: 222
    environment_id: 333
    dbt_version:
    name: test_job
    settings:
      threads: 4
      target_name: default
    execution:
      timeout_seconds: 0
    deferring_job_definition_id:
    deferring_environment_id:
    run_generate_sources: false
    execute_steps:
      - dbt test --select jaffle_shop
    generate_docs: false
    schedule:
      cron: 9 */12 * * 0,1,2,3,4,5,6
    triggers:
      github_webhook: false
      git_provider_webhook: false
      schedule: false
      on_merge: false
    description: ''
    run_compare_changes: false
    compare_changes_flags: --select state:modified
    job_type: other
    triggers_on_draft_pr: false
    job_completion_trigger_condition:
    custom_environment_variables: []
  test_job:
    account_id: 111
    project_id: 222
    environment_id: 333
    dbt_version:
    name: test_job_2
    settings:
      threads: 4
      target_name: default
    execution:
      timeout_seconds: 0
    deferring_job_definition_id:
    deferring_environment_id:
    run_generate_sources: false
    execute_steps:
      - dbt test --select my_other_jaffle_shop
    generate_docs: false
    schedule:
      cron: 9 */12 * * 0,1,2,3,4,5,6
    triggers:
      github_webhook: false
      git_provider_webhook: false
      schedule: false
      on_merge: false
    description: ''
    run_compare_changes: false
    compare_changes_flags: --select state:modified
    job_type: other
    triggers_on_draft_pr: false
    job_completion_trigger_condition:
    custom_environment_variables: []
```

With this `jobs.yml` config, there were a couple of different scenarios we tried:

**First scenario:** 
* Create `test_job` > run `plan`/`sync`> `test_job` is created in dbt Cloud.
* Add another job with a key of `test_job` with name `test_job_2` to my `jobs.yml`, which returned the following:

```bash
2025-05-07 21:03:57.458 | INFO     | dbt_jobs_as_code.cloud_yaml_mapping.change_set:build_change_set:251 - Checking for differences in test_job
❌ Job test_job is different - Diff:
{
  "job_id": "test_job",
  "status": "different",
  "differences": {
    "values_changed": {
      "root['name']": {
        "new_value": "test_job_2",
        "old_value": "test_job"
      }
    }
  }
}
2025-05-07 21:03:58.173 | INFO     | dbt_jobs_as_code.main:plan:201 - -- PLAN -- 1 changes detected.
[21:03:58]                Changes detected                           main.py:203
           ┏━━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓                      
           ┃ Action ┃ Type ┃ ID       ┃ Proj ID ┃ Env ID ┃                      
           ┡━━━━━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩                      
           │ UPDATE │ Job  │ test_job │ 222     │ 333    │                      
           └────────┴──────┴──────────┴─────────┴────────┘      
```

**Second scenario:**
* Have no existing jobs defined called `test_job` in code
* Add 2 jobs at the same time with the same key name
* Run a `plan`, it will do the following:

```bash
2025-05-07 21:09:39.880 | INFO     | dbt_jobs_as_code.main:plan:201 - -- PLAN -- 1 changes detected.
[21:09:39]                 Changes detected                          main.py:203
           ┏━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓                    
           ┃ Action ┃ Type ┃ ID         ┃ Proj ID ┃ Env ID ┃                    
           ┡━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩                    
           │ CREATE │ Job  │ test_job_2 │ 222     │ 333    │                    
           └────────┴──────┴────────────┴─────────┴────────┘         
```

If I had to guess, I would think this may be happening due to the way that the JSON python library will drop duplicate keys when doing a `json.loads()` and/or `json.dumps()`, so if there would be a way to (especially in the `validate` command) check if duplicate keys exist first, and have a configurable flag to throw an error or not, I think that would be really helpful.
 
**Who will this benefit?**
Developers and/or Platform teams that want to enforce code standards and make sure jobs aren't potentially getting dropped by manual input errors into the `jobs.yml` file.

**Are you interested in contributing this feature?**
Yes, would be happy to help contribute if need be.
