### ISSUE TITLE
Dig on the correct syntax for `schedule`

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-jobs-as-code#4]
The following syntaxes are correct, but it would be great to come up with the "rules" saying what combination of `cron/date/time` is allowed from the API.

Could we actually simplify it and let people maintain a simple version that we would "transform" into the correct API format?

```
    schedule:
      cron: "0 */2 * * *"
      date:
        cron: "0 */2 * * *"
        type: "custom_cron"
      time:
        type: "every_hour"
        interval: 1
    triggers:
      custom_branch_only: true
      git_provider_webhook: false
      github_webhook: false
      schedule: true
```

```
    schedule:
      cron: "0 * * * *"
      date:
        cron: "0 * * * *"
        type: "custom_cron"
      time:
        hours: null
        interval: 1
        type: every_hour
    triggers:
      custom_branch_only: true
      git_provider_webhook: false
      github_webhook: true # this job runs from webhooks
      schedule: false # this doesn't run on a schedule
```
