### ISSUE TITLE
[Feature] Add ability to template jobs for different environments and "promote" jobs

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-jobs-as-code#70]
**Describe the feature**

Adding the ability to manage promoting jobs between environment by templating the jobs for different job IDs and environment IDs

**Describe alternatives you've considered**

We could allow people to define the following files

```
# jobs.yml
- job_1:
  - project_id: {{ proj_1 }}
  - environment_id: {{ env_1 }}
  - name: ...
  ...
- job_2:
  - project_id: {{ proj_1 }}
  - environment_id: {{ env_2 }}
  - name: ...
  ...
```

```
# dev-vars.yml
proj_1: 123
env_1: 234
env_2: 345 
```

```
# prod-vars.yml
proj_1: 987
env_1: 765
env_2: 543 
```

And people could manage dev jobs with
```
dbt-jobs-as-code job.yml --var-file dev-vars.yml
```
and prod jobs with
```
dbt-jobs-as-code job.yml --var-file prod-vars.yml
```

Additionally, we could have a flag to limit the project IDs / environment IDs to the ones in the generated YML files as an alternative to defining `-p` and `-e` filters.

Ideas for the flag name (I don't really like any 😄, and I am open to suggestions) :
- `--restrict-envs-in-yml`
- `--envs-in-yml-only`
- `--partial-envs`
- `--restrict`
- `--filtered`
- ???

To consider:
- [ ] Manage the case where people add Jinja to the job file but don't provide the vars
- [ ] Manage the case where only some vars where added
- [ ] Handle the case when we use templating with `-p`/`-e` and/or `--restrict` and/or no filter
